# Generated by Django 5.2.1 on 2025-06-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='tipificacion',
            field=models.CharField(choices=[('NO CONTESTA', 'NO CONTESTA'), ('DATO FALSO', 'DATO FALSO'), ('NO INTERESADO - POR PROYECTO', 'NO INTERESADO - POR PROYECTO'), ('FUERA DE SERVICIO', 'FUERA DE SERVICIO'), ('NO REGISTRADO', 'NO REGISTRADO'), ('VOLVER A LLAMAR', 'VOLVER A LLAMAR'), ('APAGADO', 'APAGADO'), ('SEGUIMIENTO', 'SEGUIMIENTO'), ('NO INTERESADO - MEDIOS ECONOMICOS', 'NO INTERESADO - MEDIOS ECONOMICOS'), ('CITA - ZOOM', 'CITA - ZOOM'), ('NO INTERESADO - UBICACION', 'NO INTERESADO - UBICACION'), ('NO INTERESADO - YA COMPRO EN OTRO LUGAR', 'NO INTERESADO - YA COMPRO EN OTRO LUGAR'), ('INFORMACION WSP/CORREO', 'INFORMACION WSP/CORREO'), ('TERCERO', 'TERCERO'), ('NO INTERESADO - LEGALES', 'NO INTERESADO - LEGALES'), ('CITA - SALA', 'CITA - SALA'), ('CITA - PROYECTO', 'CITA - PROYECTO'), ('CITA - POR CONFIRMAR', 'CITA - POR CONFIRMAR'), ('CITA - HxH', 'CITA - HxH'), ('YA ASISTIO', 'YA ASISTIO'), ('DUPLICADO', 'DUPLICADO'), ('YA ES PROPIETARIO', 'YA ES PROPIETARIO'), ('AGENTE INMOBILIARIO', 'AGENTE INMOBILIARIO'), ('GESTON WSP', 'GESTON WSP'), ('NO CALIFICA', 'NO CALIFICA')], default='Nuevo', max_length=100),
        ),
    ]
