# Generated by Django 5.2.1 on 2025-06-05 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_alter_lead_distrito_alter_lead_medio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='leads.appointment'),
        ),
    ]
