# Generated by Django 5.2.1 on 2025-06-05 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_action_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='has_ever_been_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
