# Generated by Django 5.2.1 on 2025-06-06 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_appointment_has_ever_been_confirmed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='opc',
            new_name='opc_original',
        ),
        migrations.AddField(
            model_name='lead',
            name='calle_o_modulo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='fecha_captacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='OPCPersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('rol', models.CharField(choices=[('OPC', 'Personal OPC'), ('SUPERVISOR', 'Supervisor OPC')], max_length=10)),
                ('horario_semanal', models.JSONField(blank=True, default=dict, null=True)),
                ('supervisor', models.ForeignKey(blank=True, limit_choices_to={'rol': 'SUPERVISOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinados', to='leads.opcpersonnel')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opc_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='opc_personal_atendio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_atendidas_opc', to='leads.opcpersonnel'),
        ),
        migrations.AddField(
            model_name='lead',
            name='personal_opc_captador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_captados', to='leads.opcpersonnel'),
        ),
        migrations.AddField(
            model_name='lead',
            name='supervisor_opc_captador',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'SUPERVISOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_supervisados', to='leads.opcpersonnel'),
        ),
    ]
