# Generated by Django 5.2.1 on 2025-06-06 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_rename_opc_lead_opc_original_lead_calle_o_modulo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='opc_original',
        ),
    ]
