# Generated by Django 5.2.1 on 2025-06-06 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_alter_action_lead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='proyecto',
        ),
        migrations.AddField(
            model_name='lead',
            name='proyecto_interes',
            field=models.CharField(blank=True, choices=[('OASIS 2 (AUCALLAMA)', 'OASIS 2 (AUCALLAMA)'), ('OASIS 3 (HUACHO 2)', 'OASIS 3 (HUACHO 2)'), ('OASIS 1 (HUACHO 1)', 'OASIS 1 (HUACHO 1)'), ('OASIS 1 y 2', 'OASIS 1 y 2'), ('OASIS 2 y 3', 'OASIS 2 y 3'), ('OASIS 1 y 3', 'OASIS 1 y 3'), ('OASIS 1,2 y 3', 'OASIS 1,2 y 3')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='calle_o_modulo',
            field=models.CharField(blank=True, choices=[('CALLE', 'Calle'), ('MODULO', 'Módulo')], max_length=10, null=True),
        ),
    ]
