# Generated by Django 5.2.1 on 2025-06-20 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_remove_lead_proyecto_lead_proyecto_interes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadDuplicate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('celular', models.CharField(max_length=20)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_interaccion', models.DateField(blank=True, null=True)),
                ('fecha_importacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(default='pendiente', max_length=20)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('observacion_opc', models.TextField(blank=True, null=True)),
                ('proyecto_interes', models.CharField(blank=True, max_length=50, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True)),
                ('medio', models.CharField(blank=True, max_length=100, null=True)),
                ('distrito', models.CharField(blank=True, max_length=100, null=True)),
                ('tipificacion', models.CharField(blank=True, max_length=100, null=True)),
                ('calle_o_modulo', models.CharField(blank=True, max_length=10, null=True)),
                ('asesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('captador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.opcpersonnel')),
                ('original_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='leads.lead')),
            ],
        ),
    ]
