# Generated by Django 5.2.1 on 2025-06-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_leadduplicate'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='es_lead_opc',
            field=models.BooleanField(default=False, help_text='Indica si este lead fue captado por personal OPC'),
        ),
    ]
