# Generated by Django 5.2.1 on 2025-06-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_lead_es_lead_opc'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='es_directeo',
            field=models.BooleanField(default=False, help_text='Indica si el lead fue captado y gestionado completamente por OPC (directeo)'),
        ),
        migrations.AddField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('OPERADOR', 'Operador'), ('ASESOR_PRESENCIAL', 'Asesor Presencial'), ('OPC', 'Personal OPC')], default='OPERADOR', help_text='Rol principal del usuario en el CRM', max_length=30),
        ),
    ]
